<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2015
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Plugin
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['PLUGINS']['cc_frontedit'] = array('CustomCatalog Frontend Editing','Dieses Plugin stellt für das CustomCatalog Plugin Bearbeitungsmöglichkeiten für Frontend-Benutzer bereit.');


/**
 * Frontend texts
 */
#$GLOBALS['TL_LANG']['customelements_notelist']['submitLabel'] 			= 'Auf Merkliste';
#$GLOBALS['TL_LANG']['customelements_notelist']['amountLabel'] 			= 'Menge';
#$GLOBALS['TL_LANG']['customelements_notelist']['removeLabel'] 			= 'Entfernen';
#$GLOBALS['TL_LANG']['customelements_notelist']['updateLabel'] 			= 'Aktualisieren';
#$GLOBALS['TL_LANG']['customelements_notelist']['emptyLabel'] 			= '-';
#$GLOBALS['TL_LANG']['customelements_notelist']['emptyInfo'] 			= 'Ihre Merkliste ist leer.';
#$GLOBALS['TL_LANG']['customelements_notelist']['pleaseSelect'] 			= 'Bitte wählen Sie';
#$GLOBALS['TL_LANG']['customelements_notelist']['itemAdded'] 			= 'Der Eintrag wurde auf die Merkliste gelegt.';
#$GLOBALS['TL_LANG']['customelements_notelist']['itemUpdated'] 			= 'Der Eintrag wurde aktualisiert.';
#$GLOBALS['TL_LANG']['customelements_notelist']['blankOption'] 			= '-';
