<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2015
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Plugin
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['PLUGINS']['cc_frontedit'] = array('CustomCatalog Frontend Editing','Dieses Plugin stellt für das CustomCatalog Plugin Bearbeitungsmöglichkeiten für Frontend-Benutzer bereit.');


/**
 * Frontend texts
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG_FRONTEDIT']['MSC']['enable'][0] = 'Frontedit aktivieren';
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG_FRONTEDIT']['MSC']['enable'][1] = 'Aktivert die Frontedit Funktionen';
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG_FRONTEDIT']['MSC']['submit_save']	 = 'Speichern';
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG_FRONTEDIT']['MSC']['submit_delete']	 = 'Löschen';
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG_FRONTEDIT']['MSC']['submit_edit']	 = 'Bearbeiten';
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG_FRONTEDIT']['MSC']['submit_override'] = 'Überschreiben';
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG_FRONTEDIT']['MSC']['submit_copy']	 = 'Kopieren';
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG_FRONTEDIT']['MSC']['submit_cut']	 	= 'Verschieben';