<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2015
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */


$GLOBALS['TL_LANG']['XPT']['cc_edit_noPermission'] 				= 'Keine FrontEdit Rechte';
$GLOBALS['TL_LANG']['XPT']['cc_edit_noPermission_info'] 		= 'Ihr Benutzer verfügt über unzureichende Rechte zum Bearbeiten dieses Eintrags.';
$GLOBALS['TL_LANG']['XPT']['cc_edit_noPermission_hint'] 		= '';
$GLOBALS['TL_LANG']['XPT']['cc_edit_noPermission_referer'] 		= 'Klicken Sie diesen Link %s, um die Bearbeitungsebene zu verlassen.';