<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2015
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['MOD']['pct_customelements_plugin_cc_frontedit'] 	= 'PCT CustomCatalog FrontEdit Plugin '.PCT_CUSTOMELEMENTS_PLUGIN_CC_FRONTEDIT_VERSION.' (PCT CustomElement Plugin)';
$GLOBALS['TL_LANG']['FMD']['customcatalogfrontedit'][0]					= 'CustomCatalog-FrontendEditor';
$GLOBALS['TL_LANG']['FMD']['customcatalogfrontedit'][1]					= 'Erstellt ein Leserähnliches-Modul zum Bearbeiten von CustomCatalog Einträgen';