<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2015
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_member']['customcatalog_edit_active'][0] = 'Gruppenrechte erweitern';
$GLOBALS['TL_LANG']['tl_member']['customcatalog_edit_active'][1] = 'Wählen Sie hier um die Frontedit-Funktionen bereitzustellen und gesetzte Gruppenrechte zu erweitern.';
$GLOBALS['TL_LANG']['tl_member']['customcatalog_edit_disable'][0] = 'Mitglied sperren';
$GLOBALS['TL_LANG']['tl_member']['customcatalog_edit_disable'][1] = 'Wählen Sie hier alle Frontedit Funtkionen für dieses Mitglied zu sperren.';

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_member']['frontedit_legend'] = 'CustomCatalog FrontEdit-Einstellungen';