<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2015
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_module']['customcatalog_edit_active'][0] = 'Aktivieren';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_edit_active'][1] = 'Wählen Sie hier um die Frontedit-Funktionen bereitzustellen';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_edit_showUnpublished'][0] = 'Nicht veröffentlichte Einträge anzeigen';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_edit_showUnpublished'][1] = 'Wählen Sie hier um auch nicht veröffentlichte Einträge in der Liste anzeigen zu lassen.';

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_module']['frontedit_legend'] = 'FrontEdit-Einstellungen';