<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2015
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['notEditable'] = array('Nicht editierbar','Dieses Attribute ist vor dem Bearbeiten im Frontend schützen.');


/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['frontedit_legend'] = 'FrontEdit-Einstellungen';