<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2015
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_settings']['customcatalog_edit_admin'] 		= array('Admin-Benutzer für Versionierung','Wählen Sie den Benutzer, der für Versionierungsdatensätze genutzt werden soll. Leere Auswahl = Benutzer mit ID=1 (ggf. keine Versionierung)');

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_settings']['customcatalog_edit_legend'] 		= 'CustomCatalog-FrontEdit-Einstellungen';